import { Component } from '@angular/core';
import { EmployeeCardComponent } from '../employee-card/employee-card.component';

@Component({
  selector: 'app-overview',
  standalone: true,
  imports: [EmployeeCardComponent],
  templateUrl: './overview.component.html',
  styleUrl: './overview.component.scss',
})
export class OverviewComponent {
  employees = [
    {
      name: 'Emma Johnson',
      role: 'Backend Developer',
      experience: 7,
      employee_rating: 4,
      current_team: 'IDC',
      reporting_manager: 'Lalit Agrawal',
      mobile_number: '9123456789',
      email: 'emma@infrrd.ai',
    },
    {
      name: 'James Smith',
      role: 'Full Stack Developer',
      experience: 6,
      employee_rating: 5,
      current_team: 'Radian',
      reporting_manager: 'Lalit Agrawal',
      mobile_number: '9234567890',
      email: 'james@infrrd.ai',
    },
    {
      name: 'Olivia Brown',
      role: 'UI/UX Designer',
      experience: 4,
      employee_rating: 3,
      current_team: 'Product Team',
      reporting_manager: 'Lalit Agrawal',
      mobile_number: '9345678901',
      email: 'olivia@infrrd.ai',
    },
    {
      name: 'Liam Davis',
      role: 'DevOps Engineer',
      experience: 8,
      employee_rating: 4,
      current_team: 'Rustify',
      reporting_manager: 'Lalit Agrawal',
      mobile_number: '9456789012',
      email: 'liam@infrrd.ai',
    },
    {
      name: 'Sophia Martinez',
      role: 'Data Scientist',
      experience: 5,
      employee_rating: 4,
      current_team: 'OCBC',
      reporting_manager: 'Lalit Agrawal',
      mobile_number: '9567890123',
      email: 'sophia@infrrd.ai',
    },
    {
      name: 'Noah Wilson',
      role: 'QA Engineer',
      experience: 3,
      employee_rating: 3,
      current_team: 'Radian',
      reporting_manager: 'Lalit Agrawal',
      mobile_number: '9678901234',
      email: 'noah@infrrd.ai',
    },
    {
      name: 'Ava Taylor',
      role: 'Software Architect',
      experience: 10,
      employee_rating: 5,
      current_team: 'Product Team',
      reporting_manager: 'Lalit Agrawal',
      mobile_number: '9789012345',
      email: 'ava@infrrd.ai',
    },
    {
      name: 'Ethan Anderson',
      role: 'Systems Analyst',
      experience: 6,
      employee_rating: 4,
      current_team: 'IDC',
      reporting_manager: 'Lalit Agrawal',
      mobile_number: '9890123456',
      email: 'ethan@infrrd.ai',
    },
    {
      name: 'Isabella Thomas',
      role: 'Network Engineer',
      experience: 7,
      employee_rating: 4,
      current_team: 'Rustify',
      reporting_manager: 'Lalit Agrawal',
      mobile_number: '9901234567',
      email: 'isabella@infrrd.ai',
    },
    {
      name: 'Mason Lee',
      role: 'Security Engineer',
      experience: 5,
      employee_rating: 4,
      current_team: 'OCBC',
      reporting_manager: 'Lalit Agrawal',
      mobile_number: '9012345678',
      email: 'mason@infrrd.ai',
    },
    {
      name: 'Charlotte Harris',
      role: 'Technical Writer',
      experience: 4,
      employee_rating: 3,
      current_team: 'Radian',
      reporting_manager: 'Lalit Agrawal',
      mobile_number: '9123456781',
      email: 'charlotte@infrrd.ai',
    },
    {
      name: 'Amelia Clark',
      role: 'Product Manager',
      experience: 9,
      employee_rating: 5,
      current_team: 'Product Team',
      reporting_manager: 'Lalit Agrawal',
      mobile_number: '9234567892',
      email: 'amelia@infrrd.ai',
    },
    {
      name: 'Lucas Rodriguez',
      role: 'Cloud Engineer',
      experience: 7,
      employee_rating: 4,
      current_team: 'IDC',
      reporting_manager: 'Lalit Agrawal',
      mobile_number: '9345678902',
      email: 'lucas@infrrd.ai',
    },
    {
      name: 'Mia Walker',
      role: 'Business Analyst',
      experience: 5,
      employee_rating: 4,
      current_team: 'Rustify',
      reporting_manager: 'Lalit Agrawal',
      mobile_number: '9456789013',
      email: 'mia@infrrd.ai',
    },
    {
      name: 'Jackson Young',
      role: 'Mobile Developer',
      experience: 6,
      employee_rating: 4,
      current_team: 'OCBC',
      reporting_manager: 'Lalit Agrawal',
      mobile_number: '9567890124',
      email: 'jackson@infrrd.ai',
    },
    {
      name: 'Harper King',
      role: 'Game Developer',
      experience: 8,
      employee_rating: 5,
      current_team: 'Radian',
      reporting_manager: 'Lalit Agrawal',
      mobile_number: '9678901235',
      email: 'harper@infrrd.ai',
    },
    {
      name: 'Ella Scott',
      role: 'Database Administrator',
      experience: 4,
      employee_rating: 3,
      current_team: 'Product Team',
      reporting_manager: 'Lalit Agrawal',
      mobile_number: '9789012346',
      email: 'ella@infrrd.ai',
    },
  ];
}
